### ISSUE TITLE
Multipurpose or Discrete devices?

### ISSUE THREAD

**Issue by f34rdotcom** [HubitatCommunity/Hubitat-AlarmDecoder#6]
I continue to find issues with having the Away button an indicator and a momentary. At least with Amazon Echo it does not see these devices as indicators only buttons so I can not create Alexa routines based upon them directly. I am seriously considering another big re-factor to split the Momentary Indicator devices into a Momentary device and a similarly named Contact device.

Input please!

**Comment by raidflex** [comment]
I currently have Google Home's and the away/stay devices are seen as "buttons" in GH also. Although if I arm the system from HSM, the switch's status does update to "on."

Discrete devices might be a better solution though.

**Comment by f34rdotcom** [comment]
Ok I was able to keep momentary buttons with some changes and added Contact sensors. Everyring loads very nicely into a Dashboard.
